# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# OpenWeb SDK requires iOS 15.0+
platform :ios, '15.0'

# Toggle New Architecture: '0' = Old (Bridge), '1' = New (Fabric + TurboModules)
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'OpenWebRnSample074' do
  config = use_native_modules!

  # OpenWeb SDK for conversation feature
  # Reference: https://developers.openweb.com/docs/ios-getting-started
  pod 'OpenWebSDK'

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'OpenWebRnSample074Tests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
